"""
Marker information extraction and reporting module for MultiChSync.

This module extracts metadata and statistics from marker CSV files
generated by the MultiChSync pipeline, and generates comprehensive reports.
"""

import re
from pathlib import Path

import pandas as pd
import numpy as np
from typing import Union, Optional, List, Dict, Tuple
import logging

# =========================================================
# Configuration
# =========================================================
# Default column names for marker CSV files
# These will be auto-detected from actual file headers
POSSIBLE_TIME_COLS = ["reference_time", "Time(sec)", "time", "Time", "referencetime"]
POSSIBLE_VALUE_COLS = ["value", "Value"]
POSSIBLE_INDEX_COLS = ["index", "Index", ""]  # empty string for unnamed index


# =========================================================
# Helper functions
# =========================================================
def infer_device_from_name(fname: str) -> str:
    """
    Infer device/modality from filename keywords.

    Returns:
        Device name: 'fnirs', 'eeg', 'ecg', 'eda', 'emg', 'resp', or 'unknown'
        Note: 'marker' is not considered a device type.
    """
    s = fname.lower()

    if "fnirs" in s or "nirs" in s:
        return "fnirs"
    if "eeg" in s:
        return "eeg"
    if "ecg" in s or "ekg" in s:
        return "ecg"
    if "eda" in s or "gsr" in s:
        return "eda"
    if "emg" in s:
        return "emg"
    if "resp" in s:
        return "resp"
    # Note: 'marker' is not a device type, so we don't return it
    # if "marker" in s or "trigger" in s:
    #     return "marker"
    return "unknown"


def infer_device_from_path(path: Path) -> str:
    """
    Infer device/modality from file path.

    Checks path parts for known device subdirectories (ecg, eeg, fnirs, etc.)
    and also checks data/raw and data/convert subdirectories.

    Returns:
        Device name: 'fnirs', 'eeg', 'ecg', or 'unknown'
    """
    parts = [p.lower() for p in path.parts]

    # Device mapping: directory name -> device type
    device_map = {
        "ecg": "ecg",
        "eeg": "eeg",
        "fnirs": "fnirs",
        "nirs": "fnirs",
        "eda": "eda",
        "emg": "emg",
        "resp": "resp",
    }

    # First, check for exact directory name matches (excluding filename)
    # Traverse from parent directories up to root
    # Skip generic directory names that don't indicate device type
    skip_dirs = {
        "marker",
        "data",
        "raw",
        "convert",
        "info",
        "cleaned",
        "output",
        "input",
    }

    for i in range(len(parts) - 1):  # Exclude filename part (last element)
        dir_name = parts[i]
        if dir_name in skip_dirs:
            continue
        if dir_name in device_map:
            return device_map[dir_name]

    # Second, check for directory names containing device keywords
    for i in range(len(parts) - 1):  # Exclude filename
        dir_name = parts[i]
        for keyword, device in device_map.items():
            if keyword in dir_name:
                return device

    # Third, check if path contains data/raw or data/convert subdirectories
    try:
        # Look for pattern like .../data/raw/ecg/... or .../data/convert/eeg/...
        for i in range(len(parts) - 2):
            if parts[i] in ["data", "raw", "convert"] and parts[i + 1] in device_map:
                return device_map[parts[i + 1]]
            if (
                parts[i] == "data"
                and parts[i + 1] in ["raw", "convert"]
                and parts[i + 2] in device_map
            ):
                return device_map[parts[i + 2]]
    except IndexError:
        pass

    # Finally, fallback to filename inference
    filename_device = infer_device_from_name(path.name)
    if filename_device != "unknown":
        return filename_device

    # If filename gives 'unknown', try to infer from parent directory patterns
    # Check if any parent directory name suggests a device type
    for i in range(len(parts) - 1):
        dir_name = parts[i]
        if "ecg" in dir_name:
            return "ecg"
        elif "eeg" in dir_name:
            return "eeg"
        elif "fnirs" in dir_name or "nirs" in dir_name:
            return "fnirs"
        elif "eda" in dir_name:
            return "eda"
        elif "emg" in dir_name:
            return "emg"
        elif "resp" in dir_name:
            return "resp"

    return "unknown"


def safe_read_csv(csv_path: Path) -> pd.DataFrame:
    """
    Try multiple encodings to read CSV robustly.

    Returns:
        DataFrame with the CSV data

    Raises:
        Exception if all encodings fail
    """
    encodings = ["utf-8-sig", "utf-8", "gbk", "gb2312", "latin1"]
    last_err = None

    for enc in encodings:
        try:
            df = pd.read_csv(csv_path, encoding=enc)
            # Remove byte-order-mark induced column if present
            if df.columns[0].startswith("\ufeff"):
                df = df.rename(
                    columns={df.columns[0]: df.columns[0].replace("\ufeff", "")}
                )
            return df
        except Exception as e:
            last_err = e

    raise last_err


def detect_marker_columns(df: pd.DataFrame) -> Tuple[str, str, str]:
    """
    Detect the actual column names for index, time, and value in marker CSV.

    Args:
        df: DataFrame read from marker CSV

    Returns:
        Tuple of (index_col, time_col, value_col)

    Raises:
        ValueError if required columns cannot be detected
    """
    # Detect index column (first column, often unnamed)
    index_col = df.columns[0]
    if index_col == "" or "Unnamed: 0" in index_col:
        # This is the default pandas index column
        index_col = "index"

    # Detect time column
    time_col = None
    for possible in POSSIBLE_TIME_COLS:
        if possible in df.columns:
            time_col = possible
            break

    if time_col is None:
        # Try case-insensitive match
        for col in df.columns:
            if col.lower() in [c.lower() for c in POSSIBLE_TIME_COLS]:
                time_col = col
                break

    # Detect value column
    value_col = None
    for possible in POSSIBLE_VALUE_COLS:
        if possible in df.columns:
            value_col = possible
            break

    if value_col is None:
        # Try case-insensitive match
        for col in df.columns:
            if col.lower() in [c.lower() for c in POSSIBLE_VALUE_COLS]:
                value_col = col
                break

    if time_col is None:
        raise ValueError(
            f"Could not detect time column in DataFrame. Columns: {list(df.columns)}"
        )

    # Value column is optional - some marker files may only have time
    if value_col is None:
        value_col = "value"  # default name

    return index_col, time_col, value_col


def parse_filename(fname: str) -> dict:
    """
    Parse filename into metadata components.

    Supported patterns:
    1) BIDS format: sub-xxx_ses-xx_task-xxx_modality
       examples: sub-060_ses-01_task-rest_fnirs.csv, sub-060_ses-00_task-picture_eeg.set
    2) yyyymmddnnn... (date + subject)
       examples: 20251101060_1_marker.csv, 20251101060part1_marker.csv
    3) PPPP_nnn_SEG_* (project + subject + segment)
       examples: WJTB_017_SEG_01_task_eeg.csv

    Returns:
        Dictionary with keys: filename, stem, subject_id, session_label,
        sequence_id, project, filename_style, device
    """
    stem = Path(fname).stem
    device = infer_device_from_name(fname)

    result = {
        "filename": fname,
        "stem": stem,
        "subject_id": None,
        "session_label": None,
        "sequence_id": None,
        "project": None,
        "filename_style": "unmatched",
        "device": device,
    }

    # -----------------------------------------------------
    # Pattern A: BIDS format sub-xxx_ses-xx_task-xxx_modality
    # -----------------------------------------------------
    # examples: sub-060_ses-01_task-rest_fnirs.csv
    #           sub-060_ses-00_task-picture_eeg.set
    #           sub-060_ses-01_task-rest_ecg.acq
    p_bids = re.match(
        r"^sub-(?P<subj>\d+)_ses-(?P<ses>\d+)_task-(?P<task>\w+)_(?P<mod>\w+)$",
        stem,
        flags=re.IGNORECASE,
    )
    if p_bids:
        subj = p_bids.group("subj")
        ses = p_bids.group("ses")
        task = p_bids.group("task")
        modality = p_bids.group("mod")

        # Determine device from modality
        if modality.lower() in ["fnirs", "nirs"]:
            device = "fnirs"
        elif modality.lower() == "eeg":
            device = "eeg"
        elif modality.lower() in ["ecg", "ekg"]:
            device = "ecg"

        result.update(
            {
                "subject_id": subj.zfill(3),  # Ensure 3 digits
                "session_label": f"ses-{ses.zfill(2)}",
                "sequence_id": ses.zfill(2),
                "project": None,
                "filename_style": "bids",
                "device": device,
            }
        )
        return result

    # -----------------------------------------------------
    # Pattern B: yyyymmddnnn... (date + subject)
    # -----------------------------------------------------
    # date(8) + subject(3) + optional _seq or partseq
    # examples: 20250516017, 20250516017_02, 20250516017part1
    p_date = re.match(
        r"^(?P<date>\d{8})(?P<subj>\d{3})(?:part(?P<part>\d+)|_(?P<seq>\d{1,2}))?(?:_|$)",
        stem,
        flags=re.IGNORECASE,
    )
    if p_date:
        date = p_date.group("date")
        subj = p_date.group("subj")
        part = p_date.group("part")
        seq = p_date.group("seq")

        sequence_id = None
        if part is not None:
            sequence_id = f"{int(part):02d}"
        elif seq is not None:
            sequence_id = f"{int(seq):02d}"
        else:
            sequence_id = "01"

        result.update(
            {
                "subject_id": subj,
                "session_label": date,
                "sequence_id": sequence_id,
                "project": None,
                "filename_style": "date_subject",
            }
        )
        return result

    # -----------------------------------------------------
    # Pattern C: PPPP_nnn_SEG_* (project + subject + segment)
    # -----------------------------------------------------
    p_seg = re.match(
        r"^(?P<proj>[A-Za-z]{4})_(?P<subj>\d{3})_SEG_(?P<seg>\d+)(?:_|$)",
        stem,
        flags=re.IGNORECASE,
    )
    if p_seg:
        proj = p_seg.group("proj").upper()
        subj = p_seg.group("subj")
        seg = p_seg.group("seg")

        result.update(
            {
                "subject_id": subj,
                "session_label": proj,
                "sequence_id": f"{int(seg):02d}",
                "project": proj,
                "filename_style": "project_subject_seg",
            }
        )
        return result

    # -----------------------------------------------------
    # Pattern D: Subject-only (just 3 digits)
    # -----------------------------------------------------
    m_subj = re.match(r"^(\d{3})(?:_|$)", stem)
    if m_subj:
        result.update(
            {
                "subject_id": m_subj.group(1),
                "session_label": "unknown",
                "sequence_id": "01",
                "filename_style": "subject_only",
            }
        )
        return result

    # -----------------------------------------------------
    # Fallback heuristics
    # -----------------------------------------------------
    # try to find subject as standalone 3 digits
    m_subj = re.search(r"(?:^|_)(\d{3})(?:_|$)", stem)
    if m_subj:
        result["subject_id"] = m_subj.group(1)

    # try SEG number
    m_seg = re.search(r"(?:^|_)SEG_(\d+)(?:_|$)", stem, flags=re.IGNORECASE)
    if m_seg:
        result["sequence_id"] = f"{int(m_seg.group(1)):02d}"

    # try date at start
    m_date = re.match(r"^(\d{8})", stem)
    if m_date:
        result["session_label"] = m_date.group(1)

    # try 4-letter project at start
    m_proj = re.match(r"^([A-Za-z]{4})_", stem)
    if m_proj:
        result["project"] = m_proj.group(1).upper()
        if result["session_label"] is None:
            result["session_label"] = result["project"]

    if result["sequence_id"] is None:
        result["sequence_id"] = "01"
    if result["session_label"] is None:
        result["session_label"] = "unknown"
    if result["subject_id"] is None:
        result["subject_id"] = "unknown"

    return result


def compute_marker_metrics(df: pd.DataFrame, csv_path: Path) -> dict:
    """
    Compute marker count and duration from marker CSV.

    Args:
        df: DataFrame from marker CSV
        csv_path: Path to the CSV file (for error reporting)

    Returns:
        Dictionary with n_markers, time_start_sec, time_end_sec, duration_sec
    """
    # Check for empty or invalid DataFrames
    if df.empty:
        return {
            "n_markers": 0,
            "time_start_sec": np.nan,
            "time_end_sec": np.nan,
            "duration_sec": np.nan,
        }

    # Check for DataFrames with only an index column (empty CSV files)
    if len(df.columns) == 1 and ("Unnamed: 0" in df.columns[0] or df.columns[0] == ""):
        # This is likely an empty CSV file with only an index column
        return {
            "n_markers": 0,
            "time_start_sec": np.nan,
            "time_end_sec": np.nan,
            "duration_sec": np.nan,
        }

    try:
        index_col, time_col, value_col = detect_marker_columns(df)
    except ValueError as e:
        raise ValueError(f"{csv_path.name}: {e}")

    work = df.copy()

    # Convert time column to numeric, coercing errors to NaN
    work[time_col] = pd.to_numeric(work[time_col], errors="coerce")

    # Drop rows with NaN in time column
    work = work.dropna(subset=[time_col]).copy()

    # If value column exists, drop rows with NaN in value column
    if value_col in work.columns:
        work = work[work[value_col].notna()].copy()

    if work.empty:
        return {
            "n_markers": 0,
            "time_start_sec": np.nan,
            "time_end_sec": np.nan,
            "duration_sec": np.nan,
        }

    time_start = float(work[time_col].min())
    time_end = float(work[time_col].max())
    duration = float(time_end - time_start)

    return {
        "n_markers": int(len(work)),
        "time_start_sec": round(time_start, 6),
        "time_end_sec": round(time_end, 6),
        "duration_sec": round(duration, 6),
    }


def _exact_match_case_insensitive(filename: str, stem: str) -> bool:
    """
    Check if filename stem matches the given stem (case-insensitive exact match).

    Args:
        filename: The filename to check
        stem: The stem to match against (without extension)

    Returns:
        True if the filename stem matches exactly (case-insensitive), False otherwise
    """
    file_path = Path(filename)
    file_stem = file_path.stem
    return file_stem.lower() == stem.lower()


def _find_files_by_exact_stem(
    search_dir: Path, extensions: List[str], target_stem: str
) -> List[Path]:
    """
    Find files in directory that match the target stem exactly (case-insensitive).

    Args:
        search_dir: Directory to search in
        extensions: List of file extensions to look for (e.g., ['.set', '.vhdr'])
        target_stem: The stem (filename without extension) to match exactly

    Returns:
        List of matching file paths
    """
    results = []
    if not search_dir.exists():
        return results

    for ext in extensions:
        # Search for files with this extension
        for file_path in search_dir.rglob(f"*{ext}"):
            # Skip hidden files and system files
            if any(
                part.startswith(".") or part == "__MACOSX" for part in file_path.parts
            ):
                continue
            # Check for exact stem match (case-insensitive)
            if _exact_match_case_insensitive(file_path.name, target_stem):
                results.append(file_path)

    return results


def match_data_with_marker(
    data_files: List[Dict], marker_files: List[Union[str, Path]]
) -> Dict[Path, Optional[Path]]:
    """
    Match data files with marker files based on filename stems.

    Implements filename matching rules:
    1. Remove file extensions
    2. For marker files: remove '_input_marker' suffix if present, otherwise remove '_marker' suffix
    3. For ECG data files: remove '_input' suffix if present
    4. Case-insensitive exact stem matching

    Args:
        data_files: List of dictionaries from scan_data_files(), each must have
            'file_path' key (Path object).
        marker_files: List of paths to marker CSV files (str or Path).

    Returns:
        Dictionary mapping data file path to marker file path (or None if no match).
        Ambiguous matches (multiple possible matches) are logged as warnings and
        mapped to None.

    Examples:
        >>> data_files = [{'file_path': Path('sub-001_ses-01_task-rest_fnirs.snirf')}]
        >>> marker_files = [Path('sub-001_ses-01_task-rest_fnirs_marker.csv')]
        >>> match_data_with_marker(data_files, marker_files)
        {Path('sub-001_ses-01_task-rest_fnirs.snirf'): Path('sub-001_ses-01_task-rest_fnirs_marker.csv')}
    """
    # Convert marker files to Path objects
    marker_paths = [Path(m) if isinstance(m, str) else m for m in marker_files]

    # Preprocess marker stems: remove extension and suffix
    marker_stems = {}
    for mp in marker_paths:
        stem = mp.stem
        # Remove '_input_marker' suffix first (13 chars), then '_marker' suffix (7 chars)
        if stem.endswith('_input_marker'):
            stem = stem[:-13]  # Remove '_input_marker' suffix
        elif stem.endswith('_marker'):
            stem = stem[:-7]  # Remove '_marker' suffix
        marker_stems[mp] = stem.lower()

    # Build mapping
    mapping = {}
    for data_info in data_files:
        data_path = data_info['file_path']
        data_stem = data_path.stem

        # For ECG data files: if stem ends with '_input', remove that suffix (6 chars)
        if data_stem.endswith('_input'):
            data_stem = data_stem[:-6]

        data_stem_lower = data_stem.lower()

        # Find matching marker files
        matches = []
        for mp, marker_stem in marker_stems.items():
            if marker_stem == data_stem_lower:
                matches.append(mp)

        if len(matches) == 1:
            mapping[data_path] = matches[0]
        elif len(matches) > 1:
            logging.warning(
                f"Ambiguous match for data file {data_path.name}: "
                f"multiple marker files {[m.name for m in matches]}. "
                f"Mapping to None."
            )
            mapping[data_path] = None
        else:
            mapping[data_path] = None

    return mapping


def find_data_files_for_marker(marker_filename: str) -> List[Path]:
    """
    Find possible corresponding data files for a marker file, in priority order.

    Uses strict exact filename matching (case-insensitive) to find data files.
    All pattern-based matching logic (regex, wildcards) has been removed.

    Supports BIDS format: sub-xxx_ses-xx_task-xxx_modality_marker.csv
    Examples:
        - sub-060_ses-01_task-rest_fnirs_marker.csv → sub-060_ses-01_task-rest_fnirs.*
        - sub-060_ses-00_task-picture_eeg_marker.csv → sub-060_ses-00_task-picture_eeg.*

    Args:
        marker_filename: Name of the marker CSV file

    Returns:
        List of paths to possible data files, in priority order (first is most preferred)
        Priority: Convert directory (Data/convert/) first, then raw directory (Data/raw/) as fallback
    """
    stem = Path(marker_filename).stem

    # Remove '_marker' suffix if present to get base name
    base_name = stem
    if base_name.endswith("_marker"):
        base_name = base_name[:-7]  # Remove '_marker' (7 chars)

    # For ECG, the marker filename is like: sub-060_ses-01_task-rest_input_marker.csv
    # base_name after removing '_marker' = sub-060_ses-01_task-rest_input
    # The actual data file is: sub-060_ses-01_task-rest_input.csv (which was deleted)
    # OR: sub-060_ses-01_task-rest_ecg.csv (new format)
    # So we need to strip '_input' from base_name to get the correct search pattern
    ecg_base_name = base_name
    if base_name.endswith("_input"):
        ecg_base_name = base_name[:-6]  # Remove '_input' (6 chars)

    # Try different patterns and locations
    possible_paths = []

    # PRIORITY 1: First check converted data directories (primary source)
    # fNIRS: Data/convert/fnirs/*.snirf
    possible_paths.append(Path("Data/convert/fnirs") / f"{base_name}.snirf")

    # ECG: Data/convert/ecg/*ecg.csv or *_ch*.csv
    # Use ecg_base_name (without _input suffix) to find correct data files
    # For: sub-060_ses-01_task-rest_input_marker.csv
    # ecg_base_name = sub-060_ses-01_task-rest (strips _input suffix)
    # Should match: sub-060_ses-01_task-rest_ecg.csv, sub-060_ses-01_task-rest_ch1.csv, etc.
    # Note: _input.csv files are deleted after marker extraction, so we don't search for them
    possible_paths.append(Path("Data/convert/ecg") / f"{ecg_base_name}_ecg.csv")
    possible_paths.append(Path("Data/convert/ecg") / f"{ecg_base_name}.csv")

    # If exact matches fail, try glob pattern for ECG
    # This handles cases where _input.csv was deleted after marker extraction
    ecg_convert_dir = Path("Data/convert/ecg")
    if ecg_convert_dir.exists():
        # Use ecg_base_name (already computed above without _input suffix)
        # For: sub-060_ses-01_task-rest_input_marker.csv
        # ecg_base_name = sub-060_ses-01_task-rest (strips _input suffix)
        # Glob pattern: {ecg_base_name}_*.csv matches _ecg.csv, _ch1.csv, etc.
        try:
            glob_pattern = f"{ecg_base_name}_*.csv"
            ecg_files = list(ecg_convert_dir.glob(glob_pattern))
            for f in ecg_files:
                if f not in possible_paths:
                    possible_paths.append(f)
        except Exception:
            pass

    # EEG: Search in convert directory using exact stem matching
    eeg_convert_dir = Path("Data/convert/eeg")
    if eeg_convert_dir.exists():
        eeg_extensions = [".set", ".vhdr", ".edf", ".eeg", ".fdt"]
        eeg_files = _find_files_by_exact_stem(
            eeg_convert_dir, eeg_extensions, base_name
        )
        possible_paths.extend(eeg_files)

    # PRIORITY 2: Then check raw data directories (as fallback)
    # fNIRS raw data
    raw_fnirs_dir = Path("Data/raw/fnirs")
    if raw_fnirs_dir.exists():
        # Look for .TXT files (Shimadzu/NIRS-SPM format)
        possible_paths.append(raw_fnirs_dir / f"{base_name}.TXT")
        possible_paths.append(raw_fnirs_dir / f"{base_name}.txt")

    # ECG raw data
    raw_ecg_dir = Path("Data/raw/ECG")
    if raw_ecg_dir.exists():
        # Look for .acq files (Biopac format)
        # Use ecg_base_name (without _input suffix) to match actual file naming
        # For: sub-060_ses-01_task-rest_input_marker.csv
        # ecg_base_name = sub-060_ses-01_task-rest (strips _input suffix)
        # Should match: sub-060_ses-01_task-rest_ecg.acq
        possible_paths.append(raw_ecg_dir / f"{ecg_base_name}_ecg.acq")
        possible_paths.append(raw_ecg_dir / f"{ecg_base_name}_ecg.ACQ")
        possible_paths.append(raw_ecg_dir / f"{ecg_base_name}.acq")
        possible_paths.append(raw_ecg_dir / f"{ecg_base_name}.ACQ")

    # EEG: Search in raw EEG directories using exact stem matching
    raw_eeg_dir = Path("Data/raw/EEG")
    if raw_eeg_dir.exists():
        eeg_extensions = [".set", ".vhdr", ".edf", ".eeg", ".fdt"]
        # Search recursively in all raw EEG subdirectories
        eeg_files = _find_files_by_exact_stem(raw_eeg_dir, eeg_extensions, base_name)
        possible_paths.extend(eeg_files)

    # Return all existing paths in priority order
    existing_paths = []
    seen_paths = set()

    for path in possible_paths:
        if path.exists():
            # Resolve to absolute path to avoid duplicates from symlinks or case variations
            abs_path = path.resolve()
            if abs_path not in seen_paths:
                seen_paths.add(abs_path)
                existing_paths.append(path)

    return existing_paths


def get_data_file_duration(data_file: Path) -> Optional[float]:
    """
    Extract duration from a data file.

    Supports:
    - SNIRF files: use mne.io.read_raw_snirf
    - CSV files: infer from rows and sampling rate
    - EEG files: use mne.io.read_raw for .set, .vhdr, .edf
    - ACQ files: use bioread or neurokit2 via ecg.parser
    - Shimadzu/NIRS-SPM .TXT files: parse header for Time Range or Total Points

    Args:
        data_file: Path to the data file

    Returns:
        Duration in seconds, or None if cannot determine
    """
    try:
        # SNIRF files
        if data_file.suffix == ".snirf":
            try:
                import mne

                # Suppress MNE output
                mne.set_log_level("WARNING")
                raw = mne.io.read_raw_snirf(
                    str(data_file), preload=False, verbose=False
                )
                return raw.times[-1] if len(raw.times) > 0 else None
            except (ImportError, Exception):
                # Fallback: try to get duration from HDF5 structure
                try:
                    import h5py

                    with h5py.File(data_file, "r") as f:
                        if "/nirs/data1/dataTimeSeries" in f:
                            data = f["/nirs/data1/dataTimeSeries"]
                            if "time" in f["/nirs/data1"]:
                                time = f["/nirs/data1/time"][:]
                                if len(time) > 0:
                                    return float(time[-1] - time[0])
                            # Estimate from shape and sampling rate
                            if data.shape[0] > 0:
                                # Assume 10Hz sampling rate for fNIRS
                                return data.shape[0] / 10.0
                except Exception:
                    return None

        # CSV files (ECG)
        elif data_file.suffix == ".csv":
            try:
                import pandas as pd

                # For ECG files, try to read efficiently
                # First check if it's a large file
                file_size = data_file.stat().st_size
                if file_size > 100_000_000:  # > 100MB
                    # For large files, estimate from file size
                    # Approximate bytes per row
                    with open(data_file, "r") as f:
                        first_line = f.readline()
                        second_line = f.readline()
                    bytes_per_row = len(second_line) if second_line else len(first_line)
                    if bytes_per_row > 0:
                        n_rows_approx = file_size / bytes_per_row
                        # ECG: 250 Hz (multichsync ecg default)
                        return n_rows_approx / 250.0

                df = pd.read_csv(data_file)
                n_samples = len(df)
                # Default ECG sampling rate: 250 Hz (multichsync ecg default)
                sampling_rate = 250.0
                return n_samples / sampling_rate
            except Exception:
                return None

        # EEG files
        elif data_file.suffix in [".set", ".vhdr", ".edf", ".eeg"]:
            try:
                import mne

                # Suppress MNE output
                mne.set_log_level("WARNING")
                raw = mne.io.read_raw(str(data_file), preload=False, verbose=False)
                return raw.times[-1] if len(raw.times) > 0 else None
            except Exception:
                return None

        # ACQ files (Biopac format) - use existing ECG parser
        elif data_file.suffix.lower() in [".acq"]:
            try:
                # Import the ECG parser module
                from multichsync.ecg.parser import parse_acq_file

                parsed = parse_acq_file(str(data_file), sampling_rate=None)
                return parsed.get("duration")
            except (ImportError, Exception):
                # Fallback: estimate from file size
                try:
                    # ACQ files have headers, approximate 500 Hz sampling
                    file_size = data_file.stat().st_size
                    # Rough estimate: 4 bytes per sample per channel
                    # Assume 3 channels (ECG typical)
                    n_samples_approx = file_size / (4 * 3)
                    return n_samples_approx / 500.0
                except Exception:
                    return None

        # Shimadzu/NIRS-SPM .TXT files
        elif data_file.suffix.lower() in [".txt"]:
            try:
                with open(data_file, "r", encoding="utf-8") as f:
                    content = f.read()

                # Look for Time Range line
                import re

                time_range_match = re.search(
                    r"Time Range\s+([\d\.]+)\s+([\d\.]+)", content
                )
                if time_range_match:
                    try:
                        end_time = float(time_range_match.group(2))
                        return end_time
                    except Exception:
                        pass

                # Look for Total Points line
                total_points_match = re.search(r"Total Points\s+(\d+)", content)
                if total_points_match:
                    try:
                        total_points = int(total_points_match.group(1))
                        # Assume 10 Hz sampling for fNIRS
                        return total_points / 10.0
                    except Exception:
                        pass

                # Count data lines (lines starting with a number followed by a decimal point or space)
                data_lines = 0
                for line in content.split("\n"):
                    stripped = line.strip()
                    # Match lines starting with number like "0.000" or "0.075"
                    if re.match(r"^\s*\d+\.\d+", stripped):
                        data_lines += 1

                if data_lines > 0:
                    # Assume 10 Hz sampling for fNIRS
                    return data_lines / 10.0

                return None
            except Exception:
                return None

    except Exception:
        return None

    return None

def scan_data_files(base_dir: Optional[Union[str, Path]] = None) -> List[Dict]:
    """
    Scan Data/convert/ and Data/raw/ directories recursively for supported data files.

    Supported file extensions per modality:
    - fNIRS: .snirf, .TXT, .txt
    - EEG: .set, .vhdr, .edf, .eeg, .fdt
    - ECG: .csv, .acq, .ACQ

    For each file with supported extension, collect metadata:
    - file_path: absolute Path
    - file_name: filename only
    - stem: stem (filename without extension)
    - device: inferred from path using infer_device_from_path(file_path)
    - subject_id, session_label, sequence_id, project, filename_style: from parse_filename(file_name)
    - duration_sec: call get_data_file_duration(file_path) (may be None)

    Args:
        base_dir: Base directory to scan. If None, uses current working directory (Path.cwd()).

    Returns:
        List of dictionaries with metadata for each data file, sorted by file_path.

    Examples:
        >>> files = scan_data_files("/path/to/project")
        >>> len(files)
        5
        >>> files[0]["device"]
        'fnirs'
    """
    if base_dir is None:
        base_dir = Path.cwd()
    base_dir = Path(base_dir)

    # Mapping of device to supported extensions (case-insensitive)
    device_extensions = {
        "fnirs": {".snirf", ".txt"},
        "eeg": {".set", ".vhdr", ".edf", ".eeg", ".fdt"},
        "ecg": {".csv", ".acq"},
    }
    # All supported extensions (lowercase for comparison)
    all_extensions = {ext for exts in device_extensions.values() for ext in exts}
    # Also include uppercase variants for .TXT and .ACQ
    all_extensions.add(".txt")  # already lowercase
    all_extensions.add(".acq")
    # We'll handle case-insensitive matching by converting extension to lowercase

    # Directories to scan relative to base_dir
    scan_dirs = [
        base_dir / "Data" / "convert",
        base_dir / "Data" / "raw",
    ]

    results = []

    for scan_dir in scan_dirs:
        if not scan_dir.exists():
            continue

        # Recursively iterate over all files in scan_dir
        for file_path in scan_dir.rglob("*"):
            if not file_path.is_file():
                continue

            # Skip hidden files and system directories
            if any(part.startswith(".") or part == "__MACOSX" for part in file_path.parts):
                continue

            # Check extension (case-insensitive)
            ext = file_path.suffix.lower()
            # Special handling for .TXT (uppercase) and .ACQ (uppercase)
            # Convert to lowercase for matching
            if ext not in all_extensions:
                continue

            # Parse filename metadata
            meta = parse_filename(file_path.name)
            # Infer device from path (overrides filename-based inference)
            device = infer_device_from_path(file_path)

            # Get duration (may be None)
            duration_sec = get_data_file_duration(file_path)

            results.append({
                "file_path": file_path.resolve(),
                "file_name": file_path.name,
                "stem": file_path.stem,
                "device": device,
                "subject_id": meta["subject_id"],
                "session_label": meta["session_label"],
                "sequence_id": meta["sequence_id"],
                "project": meta["project"],
                "filename_style": meta["filename_style"],
                "duration_sec": duration_sec,
            })

    # Sort by file_path for consistent ordering
    results.sort(key=lambda x: x["file_path"])
    return results


def extract_sequence_duration(marker_filename: str) -> Optional[float]:
    """
    Extract sequence duration for a marker file.

    Args:
        marker_filename: Name of the marker CSV file

    Returns:
        Duration in seconds, or None if cannot determine
    """
    result = extract_sequence_duration_and_datafile(marker_filename)
    return result["duration"] if result else None


def extract_sequence_duration_and_datafile(marker_filename: str) -> Optional[dict]:
    """
    Extract sequence duration and data file information for a marker file.

    Args:
        marker_filename: Name of the marker CSV file

    Returns:
        Dictionary with keys "duration" (float) and "data_file" (str filename),
        or None if cannot determine duration
    """
    # Get list of possible data files in priority order
    data_files = find_data_files_for_marker(marker_filename)

    # Try each file in order until we get a valid duration
    for data_file in data_files:
        duration = get_data_file_duration(data_file)
        if duration is not None:
            return {
                "duration": duration,
                "data_file": data_file.name,  # Just the filename, not full path
                "data_file_path": str(data_file),  # Full path for debugging
            }

    # If none worked, return None
    return None


# =========================================================
# Main pipeline
# =========================================================
def extract_marker_info(
    input_dir: Union[str, Path] = "Data/marker",
    output_dir: Union[str, Path] = "Data/marker/info",
    recursive: bool = True,
) -> Dict[str, Path]:
    """
    Extract metadata and statistics from marker CSV files and generate reports.
    
    Enhanced version: scans data directories and includes all data files in reports,
    even those without corresponding marker files.

    Args:
        input_dir: Directory containing marker CSV files
        output_dir: Directory where reports will be saved
        recursive: Whether to search subdirectories recursively

    Returns:
        Dictionary with paths to generated report files

    Raises:
        FileNotFoundError if no CSV files are found
        RuntimeError if no valid files could be parsed
    """
    input_dir = Path(input_dir)
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    # -----------------------------------------------------
    # Step 1: Scan data files from Data/convert/ and Data/raw/
    # -----------------------------------------------------
    # Base directory is parent of Data/ directory (assuming standard Data/ structure)
    # input_dir is typically Data/marker, so base_dir = input_dir.parent.parent
    base_dir = input_dir.parent.parent
    data_files = scan_data_files(base_dir)
    
    # -----------------------------------------------------
    # Step 2: Scan marker CSV files
    # -----------------------------------------------------
    if recursive:
        csv_files = sorted(input_dir.rglob("*.csv"))
    else:
        csv_files = sorted(input_dir.glob("*.csv"))

    # Filter out hidden files (macOS ._ files) and system files
    csv_files = [
        f
        for f in csv_files
        if not any(part.startswith(".") or part == "__MACOSX" for part in f.parts)
    ]

    # Filter out files in the output directory (including subdirectories)
    output_dir_abs = output_dir.resolve()
    csv_files = [
        f for f in csv_files if not str(f.resolve()).startswith(str(output_dir_abs))
    ]

    # -----------------------------------------------------
    # Step 3: Match data files with marker files
    # -----------------------------------------------------
    mapping = match_data_with_marker(data_files, csv_files)
    
    # Track which marker files have been matched
    matched_marker_files = set()
    for marker_path in mapping.values():
        if marker_path is not None:
            matched_marker_files.add(marker_path.resolve())
    
    # -----------------------------------------------------
    # Step 4: Process data files (with or without markers)
    # -----------------------------------------------------
    file_rows = []
    errors = []

    for data_info in data_files:
        data_path = data_info["file_path"]
        
        try:
            # Get metadata from scan_data_files result
            meta = parse_filename(data_info["file_name"])
            device = data_info["device"]
            duration_sec = data_info["duration_sec"]
            
            # Check if this data file has a matching marker file
            marker_path = mapping.get(data_path)
            
            if marker_path is not None and marker_path.exists():
                # Data file has matching marker file
                try:
                    df = safe_read_csv(marker_path)
                    metrics = compute_marker_metrics(df, marker_path)
                    n_markers = metrics["n_markers"]
                except Exception as e:
                    # Marker file exists but cannot be read
                    errors.append({
                        "file_path": str(marker_path),
                        "file_name": marker_path.name,
                        "error": f"Failed to read marker file: {e}"
                    })
                    n_markers = 0
            else:
                # Data file has no matching marker file
                n_markers = 0
            
            # Use data file duration if available
            sequence_duration = None
            if duration_sec is not None:
                sequence_duration = round(duration_sec, 2)
            
            row = {
                "file_name": data_info["file_name"],
                "device": device,
                "subject_id": meta["subject_id"],
                "sequence_id": meta["sequence_id"],
                "n_markers": n_markers,
                "sequence_duration": sequence_duration if sequence_duration is not None else "",
            }
            file_rows.append(row)
            
        except Exception as e:
            errors.append({
                "file_path": str(data_path),
                "file_name": data_path.name,
                "error": f"Failed to process data file: {e}"
            })

    # -----------------------------------------------------
    # Step 5: Process unmatched marker files (backward compatibility)
    # -----------------------------------------------------
    for csv_path in csv_files:
        # Skip files in 'info' directories (report files from previous runs)
        if "info" in csv_path.parts:
            continue
            
        # Skip marker files that were already matched to data files
        if csv_path.resolve() in matched_marker_files:
            continue
            
        try:
            # This marker file has no matching data file - use original logic
            meta = parse_filename(csv_path.name)
            df = safe_read_csv(csv_path)
            metrics = compute_marker_metrics(df, csv_path)

            # Extract sequence duration and data file from corresponding data file
            duration_info = extract_sequence_duration_and_datafile(csv_path.name)

            if duration_info:
                sequence_duration = duration_info["duration"]
                # Keep 2 decimal places
                if sequence_duration is not None:
                    sequence_duration = round(sequence_duration, 2)
                data_file_name = duration_info["data_file"]
            else:
                sequence_duration = None
                data_file_name = ""  # Will use marker filename as fallback

            # Infer device type from file path
            device = infer_device_from_path(csv_path)

            # Use data file name if available, otherwise fallback to marker filename
            display_file_name = data_file_name if data_file_name else csv_path.name

            row = {
                "file_name": display_file_name,
                "device": device,
                "subject_id": meta["subject_id"],
                "sequence_id": meta["sequence_id"],
                "n_markers": metrics["n_markers"],
                "sequence_duration": sequence_duration
                if sequence_duration is not None
                else "",
            }
            file_rows.append(row)

        except Exception as e:
            errors.append(
                {
                    "file_path": str(csv_path),
                    "file_name": csv_path.name,
                    "error": str(e),
                }
            )

    # -----------------------------------------------------
    # Step 6: Generate reports
    # -----------------------------------------------------
    per_file_df = pd.DataFrame(file_rows)
    error_df = pd.DataFrame(errors)

    if per_file_df.empty:
        raise RuntimeError("No valid files were parsed successfully.")

    # -----------------------------------------------------
    # Save error report
    # -----------------------------------------------------
    error_path = output_dir / "report_errors.csv"
    error_df.to_csv(error_path, index=False, encoding="utf-8-sig")

    # -----------------------------------------------------
    # Save one individual report per subject
    # -----------------------------------------------------
    subject_reports = {}

    for subj, g_subj in per_file_df.groupby("subject_id", dropna=False):
        subj_name = str(subj) if pd.notna(subj) else "UNKNOWN"

        g_subj = g_subj.sort_values(
            by=["device", "sequence_id", "file_name"], na_position="last"
        )

        # Save subject report directly to output directory
        report_path = output_dir / f"subject_{subj_name}_marker_report.csv"
        g_subj.to_csv(report_path, index=False, encoding="utf-8-sig")

        subject_reports[subj_name] = report_path

    print("=" * 60)
    print("Marker information extraction completed")
    print(f"Total files      : {len(per_file_df)}")
    print(f"  Data files     : {len(data_files)}")
    print(f"  Marker files   : {len(csv_files)}")
    print(f"  Matched pairs  : {len([m for m in mapping.values() if m is not None])}")
    print(f"Subjects         : {per_file_df['subject_id'].dropna().nunique()}")
    print(f"Error files      : {len(error_df)}")
    print(f"Subject reports  : {len(subject_reports)}")
    print("-" * 60)
    print(f"Error report     : {error_path}")
    for subj_name, report_path in subject_reports.items():
        print(f"  Subject {subj_name}: {report_path.name}")
    print("=" * 60)

    return {
        "error_report": error_path,
        "subject_reports": subject_reports,
    }


# =========================================================
# CLI entry point
# =========================================================
if __name__ == "__main__":
    # For direct script execution
    import sys

    if len(sys.argv) > 1:
        input_dir = sys.argv[1]
        output_dir = sys.argv[2] if len(sys.argv) > 2 else "Data/marker/info"
        recursive = sys.argv[3].lower() == "true" if len(sys.argv) > 3 else True
    else:
        input_dir = "Data/marker"
        output_dir = "Data/marker/info"
        recursive = True

    extract_marker_info(input_dir, output_dir, recursive)
